config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :records do
    get :download_csv_by_nationality, on: :collection
    get :download_csv_by_odometer, on: :collection
  end

  root 'records#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :records
  has_many :users, through: :records
  has_many :vehicles, through: :records
end

app/models/record.rb
require 'csv'

class Record < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  belongs_to :nationality

  scope :data, -> { includes(:user, :vehicle, :nationality) }

  def self.search(search)
    if search
      Record.data.where('users.name LIKE ? OR vehicles.model LIKE ?', "%#{search}%", "%#{search}%").references(:users, :vehicles)
    else
      Record.data
    end
  end

  def self.customer_count_by_nationality
    results =  Record.data.group('nationalities.name').count('records.id')
    attributes = ['Nationality', 'Cusotmer Count']

    CSV.generate do |csv|
      csv << attributes

      results.each do |result|
        csv << result
      end
    end
  end

  def self.average_odometer_reading_by_nationality
    results =  Record.data.group('nationalities.name').average('vehicles.odometer_reading')
    attributes = ['Nationality', 'Average Odometer Reading']

    CSV.generate do |csv|
      csv << attributes

      results.each do |result|
        csv << result
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records
  has_many :vehicles, through: :records
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_one :record
  has_one :user, through: :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @record = Record.new
    @records = Record.search(params[:search])
  end

  def create
    ImportData.new(params[:file]).import
    flash[:notice] = 'Data uploaded successfully'
    redirect_to records_path
  end

  def download_csv_by_nationality
    send_data Record.customer_count_by_nationality, filename: "nationality.csv"
  end

  def download_csv_by_odometer
    send_data Record.average_odometer_reading_by_nationality, filename: "odometer.csv"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VehiclesData</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<div class="jumbotron text-center">
  <div class="jumbotron text-center">
   <h4> Upload csv </h4>
    <%= form_with url: "/records", multipart: true do |f| %>
      <div>
        <%= f.file_field :file %>
      </div>
      <%= f.submit "Upload" %>
    <% end %>
  </div>
</div>
</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <%= form_tag records_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search" %>
        </p>
      <% end %>
    </div>
    <div class="col-sm-4">
      <%= button_to "Customers by nationality", download_csv_by_nationality_records_path, method: :get, class: 'btn btn-primary text-right' %>
    </div>

    <div class="col-sm-4">
      <%= button_to "Odometer readings by nationality", download_csv_by_odometer_records_path, method: :get, class: 'btn btn-primary text-right' %>
    </div>
  </div>
</div>
</br>

<div class="container">
  <% if @records.blank? %>
    <h4>No Data Avaialble!!!</h4>
  <% else %>
    <table class="table">
      <thead>
        <th>Name</th>
        <th>Nationality</th>
        <th>Email</th>
        <th>Model</th>
        <th>Year</th>
        <th>ChassisNumber</th>
        <th>Color</th>
        <th>RegistrationDate</th>
        <th>OdometerReading</th>
      </thead>
      <tbody>
        <% @records.each do |data| %>
          <tr>
            <td><%= data.user.name %></td>
            <td>
              <%= data.nationality.name %>
            </td>
            <td>
              <%= data.user.email %>
            </td>
            <td>
              <%= data.vehicle.model %>
            </td>
            <td>
              <%= data.vehicle.year %>
            </td>
            <td>
              <%= data.vehicle.chassis_number %>
            </td>
            <td>
              <%= data.vehicle.color %>
            </td>
            <td>
              <%= data.vehicle.registration_date %>
            </td>
            <td>
              <%= data.vehicle.odometer_reading %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>